### ISSUE TITLE
Cd to an inexistent folder crashes PyCMD

### ISSUE THREAD

**Issue by santagada** [horeah/PyCmd#2]
```
C:\U\leonardo.santagada> cd Idon'texist


************************************
PyCmd has encountered a fatal error!

Traceback (most recent call last):
  File "PyCmd.py", line 555, in internal_cd
FileNotFoundError: [WinError 2] The system cannot find the file specified: b"Idon'texist"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyCmd.py", line 774, in <module>
  File "PyCmd.py", line 526, in main
  File "PyCmd.py", line 587, in run_command
  File "PyCmd.py", line 558, in internal_cd
AttributeError: 'str' object has no attribute 'decode'

Crash report written to:
  C:\Users\leonardo.santagada\AppData\Roaming\PyCmd\crash-20230110_161154.log

Press any key to exit...
************************************
```

**Comment by horeah** [comment]
This has been solved by #3 
Thanks @santagada for the report and the fix.
